### ISSUE TITLE
Can't execute package specific command after cloning. 

### ISSUE THREAD

**Issue by tomer-rockman** [stactools-packages/seabed-2030#4]
**Describe the bug**
After cloning the seabed-2030 I'm unable to run seabed-2030 commands like scripts/stac seabed-2030 create_cog

**To reproduce**

> 1. Install stactools-seabed-2030
> 2. Run scripts/stac seabed-2030 create_cog infile.nc outfile.tif
> 3.  Get error: 
% scripts/stac seabed2030 create-cog ../coraltemp_v3.1_20210803.nc output.tif
Usage: stac [OPTIONS] COMMAND [ARGS]...
Try 'stac --help' for help.
Error: No such command 'seabed2030'. `

**Additional context**
Fixed by running `scripts/update` after cloning the repo.

**Comment by bluegeo** [comment]
How are you installing the package @tomer-rockman? There is no pypi dist. yet, but you should be able to install using something like:

```bash
git clone https://github.com/stactools-packages/seabed-2030.git
cd seabed-2030
pip install .
```

**Comment by tomer-rockman** [comment]
Yea that worked perfectly!

**Comment by bluegeo** [comment]
Great. I will close this knowing that pypi is coming soon and `pip install stactools-seabed-2030` will be added to the installation docs.
