### ISSUE TITLE
Seabed-2030 netcdf to COG: COG driver not found. 

### ISSUE THREAD

**Issue by tomer-rockman** [stactools-packages/seabed-2030#5]
**Describe the bug**
When trying to execute the following `% scripts/stac seabed2030 create-cog input.nc output.tif` I receive the following error: 
`Output driver 'COG' not recognised.`

**To reproduce**

> 1. Install stactools-seabed-2030
> 2. Run `scripts/update`
> 3. Run `scripts/stac seabed2030 create-cog` command 
> 4. See error

**Expected behavior**
Expected an output COG file.

**Comment by bluegeo** [comment]
This lib uses the `stactools.core.utils.convert.cogify` method, which requires the GDAL COG driver, which is available in gdal >= 3.1. I don't think this is included in the stactools documentation. @tomer-rockman, can you elevate this to an issue in the stactools repo?
